name: Fetch and Convert AdGuard Type SRS

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install sing-box
        run: |
          set -e
          VERSION=$(curl -fsSL https://api.github.com/repos/SagerNet/sing-box/releases/latest | jq -r .tag_name)
          curl -fsSL https://github.com/SagerNet/sing-box/releases/download/${VERSION}/sing-box-${VERSION#v}-linux-amd64.tar.gz -o sing-box.tar.gz
          tar -xzf sing-box.tar.gz
          sudo install sing-box-*/sing-box /usr/local/bin/sing-box
          sing-box version

      - name: Download AdGuard filter
        run: |
          curl -fsSL \
            https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt \
            -o filter.txt

      - name: Compile to sing-box srs
        run: |
          sing-box rule-set convert \
            --type adguard \
            --output adguard.srs \
            filter.txt
            

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add adguard.srs

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update AdGuard filter"
            git push
          fi
